#!/bin/bash

# Create a new migration script with descriptive name $1
function migration:new(){
    docker run \
        --rm \
        -v $(pwd)/migrate/config.yml:/cassandra-migrate.yml \
        -v $(pwd)/migrations:/migrations \
        justdomepaul/cassandra-migrate \
        generate $1 2>/dev/null
}

# Presuming that cassandra container is up and running, sends you into cqlsh session
function cql(){
    docker exec -it cassandra cqlsh
}

# Start up cassandra and run migrations
function up(){
    down
    docker compose up -d
}

# Shutdown containers
function down(){
    docker compose down
}

# Run tests against local DB
function test(){
    cassandra_id="$(docker ps -q -f name=cassandra)"
    if [ -z "$cassandra_id" ]; then
        up
    fi

    while :; do
        migrate_id="$(docker ps -q -f name=migrate)"        
        if [ -z "$migrate_id" ]; then
            go test ./... -count=1
            break
        else
            echo "Warming up"
            sleep 3
        fi        
    done

    if [ -z "$cassandra_id" ]; then
        down
    fi
}

"$@"