keyspace: hello
profiles:
  dev:
    replication:
      class: SimpleStrategy
      replication_factor: 1
  prod:
    replication:
      class: SimpleStrategy
      replication_factor: 1
migrations_path: /migrations
